### ISSUE TITLE
Missing root tab

### ISSUE THREAD

**Issue by twiddern** [TheInsomniac/Nginx-Fancyindex-Theme#1]
Hi,

I'm missing the root tab in the theme, for example I'm using autoindex straight from the rootfolder. After I change to a subdirectory, I see the dirname on the top but there's no tab or button to get to the rootdir.

**Comment by TheInsomniac** [comment]
Unfortunately, all of the testing that I performed was done under subdirectories as the 'root' on all of my sites contain index.html files.
BUT.. I believe I know the cause though I'm uncertain how to go about fixing it in a "non-hacky" way.

On line 36 in history.js and line 10 in footer.html there is "if (segments[i] !== '')" which filters out the root node because we're splitting on '/' in document.location.pathname

Perhaps:

```
if (segments[i] != '') {
  currentPath += segments[i] + '/';
  breadcrumbs += '<a href="' +  currentPath + '">' + window.unescape(segments[i]) + '<\/a>';
} else {
  currentPath += '/';
  breadcrumbs += '<a href="' + currentPath + '">Root<\/a>';
}
```

If you'd like to try that or some change therein I'd appreciate it!

**Comment by TheInsomniac** [comment]
I just tested this and it APPEARS to work. Please try on your root folder and let me know.
Thanks!

**Comment by TheInsomniac** [comment]
Alright, I was wrong but this really DOES appear to work with the side effect (which I'll work on later) that it always shows 'Root' even if the webroot is a subpath:

```
 if (segments[i] != '') {
  currentPath += segments[i] + '/';
  breadcrumbs += '<a href="' +  currentPath + '">' + window.unescape(segments[i]) + '<\/a>';
} else if (segments.length -1 !== i) {
  currentPath += '';
  breadcrumbs += '<a href="' + currentPath + '">Root<\/a>';
}
```

The above is my 'hacky' way of checking if the item matches '' AND it's not the last element in the array..
Please try and let me know. If it works for you then I'll add a check to remove 'Root' on subpaths.

**Comment by TheInsomniac** [comment]
And finally, just because I enjoy talking to myself :)
If you'd just prefer a 'Parent Directory' folder in the file listings comment the below out in the CSS file.

```
tbody tr:first-child {
  display: none;
}
```

![screencapture at thu may 22 13 58 28 mdt 2014](https://cloud.githubusercontent.com/assets/3247741/3059445/8ce46c42-e1eb-11e3-89ce-d39b6d065e4f.png)

**Comment by twiddern** [comment]
I've just hacked your second snippet in to the code and it's working great :+1: 
You should also mention the parrent directory thing, if some is missing this.

Thanks a lot for the fast work

**Comment by PeterDaveHello** [comment]
Seems the 'Parent Directory' link will not work on first-level directory.

**Comment by drx** [comment]
The :first-child below also removes the first row when the fancy index is default sorted to something else, like date descending.

```css
tbody tr:first-child {
  display: none;
}
```
