### ISSUE TITLE
dynamic file/directory length

### ISSUE THREAD

**Issue by twiddern** [TheInsomniac/Nginx-Fancyindex-Theme#2]
I've got a 1920*1080 display and the space is not full used. See file attached 
![space](https://cloud.githubusercontent.com/assets/2402659/3058660/8b691c04-e1e2-11e3-8913-2724729656a4.PNG)
The file-/dirname gets cut, but it shouln't in my mind, if there is enough space.

**Comment by TheInsomniac** [comment]
Unfortunately this one appears to be hard coded in NGINX-FancyIndex as it truncates the item upon creation. Here's an example from the generated html (no theme applied):

```
var el = document.getElementByTagName('a')[14]
<a href=​"thisisareallylongfilenametotestthecssoutbutimnotcertainifitworksornot">​thisisareallylongfilenametotestthecssoutbutimno..>​</a>​
el.innerText
"thisisareallylongfilenametotestthecssoutbutimno..>"
```

Notice that the innerText is truncated? You'd have to recompile nginx-fancy theme without this limitation in order to fix it. Sorry!

BTW, This appears in line 713-731 in ngx_http_fancyindex_module.c - It calculates the length and then truncates it -3 to add in "..>"

FIX: If you wish to recompile: On line 55 of ngx_http_fancyindex_module.c

```
#define NGX_HTTP_FANCYINDEX_NAME_LEN 50
```

Set this to a greater number and use CSS to truncate the length if it exceeds the the width of the <td>

**Comment by twiddern** [comment]
Ahh yeah you're right. Didn't had this in my mind. Sorry for annoy you with this, I just swaped from a php indexer to to fancymodule.

Thanks for the hint =)

**Comment by TheInsomniac** [comment]
I've updated the readme to reflect these changes if anyone chooses to recompile..
